<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{f759fae6-ee2c-48d0-b49d-124e991de90b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR CONSTANT
	CONST_MAX_NUMBER_OF_EA_DEVICES	: INT:= 1;
	
	//Device Specifications
	MAX_CURRENT						: REAL;
	MAX_VOLTAGE						: REAL;
	MAX_POWER						: REAL;
	MAX_RESISTANCE					: REAL;
END_VAR

VAR
	fbEAInterface					: ARRAY [1..CONST_MAX_NUMBER_OF_EA_DEVICES] OF FB_EA_Interface;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbEAInterface[1]();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>